version: '3'
services:
  redis-cluster:
    image: 'redis:6.0-alpine'
    command: redis-cli --cluster create 172.16.0.11:6379 172.16.0.12:6380 172.16.0.13:6381 172.16.0.14:6382 172.16.0.15:6383 172.16.0.16:6384 --cluster-replicas 1 --cluster-yes
    networks:
      redis_cluster_network:
        ipv4_address: 172.16.0.10
    depends_on:
      - redis-instance-1
      - redis-instance-2
      - redis-instance-3
      - redis-instance-4
      - redis-instance-5
      - redis-instance-6
  # 1. Redis Instance
  redis-instance-1:
    image: 'redis:6.0-alpine'
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'
    volumes:
      - redis-1-data:/var/lib/redis
      - ./redis-config/redis-1.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis_cluster_network:
        ipv4_address: 172.16.0.11
  # 2. Redis Instance
  redis-instance-2:
    image: 'redis:6.0-alpine'
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6380:6380'
    volumes:
      - redis-2-data:/var/lib/redis
      - ./redis-config/redis-2.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis_cluster_network:
        ipv4_address: 172.16.0.12
  # 3. Redis Instance
  redis-instance-3:
    image: 'redis:6.0-alpine'
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6381:6381'
    volumes:
      - redis-3-data:/var/lib/redis
      - ./redis-config/redis-3.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis_cluster_network:
        ipv4_address: 172.16.0.13
  # 4. Redis Instance
  redis-instance-4:
    image: 'redis:6.0-alpine'
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6382:6382'
    volumes:
      - redis-4-data:/var/lib/redis
      - ./redis-config/redis-4.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis_cluster_network:
        ipv4_address: 172.16.0.14
  # 5. Redis Instance
  redis-instance-5:
    image: 'redis:6.0-alpine'
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6383:6383'
    volumes:
      - redis-5-data:/var/lib/redis
      - ./redis-config/redis-5.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis_cluster_network:
        ipv4_address: 172.16.0.15
  # 6. Redis Instance
  redis-instance-6:
    image: 'redis:6.0-alpine'
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6384:6384'
    volumes:
      - redis-6-data:/var/lib/redis
      - ./redis-config/redis-6.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis_cluster_network:
        ipv4_address: 172.16.0.16
volumes:
  redis-1-data:
  redis-2-data:
  redis-3-data:
  redis-4-data:
  redis-5-data:
  redis-6-data:
networks:
  redis_cluster_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24