version: '3.5'
services:
  redis-cluster:
    image: 'redis:6.0-alpine'
    command: redis-cli --cluster create 192.168.0.101:6379 192.168.0.102:6380 192.168.0.103:6381 192.168.0.104:6382 192.168.0.105:6383 192.168.0.106:6384 --cluster-replicas 1 --cluster-yes
    networks:
      redis_cluster_network:
        ipv4_address: 192.168.0.100
    depends_on:
      - redis-instance-1
      - redis-instance-2
      - redis-instance-3
      - redis-instance-4
      - redis-instance-5
      - redis-instance-6
  # 1. Redis Instance
  redis-instance-1:
    image: 'redis:6.0-alpine'
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'
    volumes:
      - redis-1-data:/var/lib/redis
      - ./redis-config/redis-1.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis_cluster_network:
        ipv4_address: 192.168.0.101
  # 2. Redis Instance
  redis-instance-2:
    image: 'redis:6.0-alpine'
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6380:6380'
    volumes:
      - redis-2-data:/var/lib/redis
      - ./redis-config/redis-2.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis_cluster_network:
        ipv4_address: 192.168.0.102
  # 3. Redis Instance
  redis-instance-3:
    image: 'redis:6.0-alpine'
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6381:6381'
    volumes:
      - redis-3-data:/var/lib/redis
      - ./redis-config/redis-3.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis_cluster_network:
        ipv4_address: 192.168.0.103
  # 4. Redis Instance
  redis-instance-4:
    image: 'redis:6.0-alpine'
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6382:6382'
    volumes:
      - redis-4-data:/var/lib/redis
      - ./redis-config/redis-4.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis_cluster_network:
        ipv4_address: 192.168.0.104
  # 5. Redis Instance
  redis-instance-5:
    image: 'redis:6.0-alpine'
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6383:6383'
    volumes:
      - redis-5-data:/var/lib/redis
      - ./redis-config/redis-5.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis_cluster_network:
        ipv4_address: 192.168.0.105
  # 6. Redis Instance
  redis-instance-6:
    image: 'redis:6.0-alpine'
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6384:6384'
    volumes:
      - redis-6-data:/var/lib/redis
      - ./redis-config/redis-6.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis_cluster_network:
        ipv4_address: 192.168.0.106
volumes:
  redis-1-data:
  redis-2-data:
  redis-3-data:
  redis-4-data:
  redis-5-data:
  redis-6-data:
networks:
  redis_cluster_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24